import os
import subprocess
import sys
import shutil


def run_command(command, description):
    """Execute a shell command with user feedback and error handling.
    
    Args:
        command: Shell command string to execute
        description: Human-readable description displayed to user
        
    Raises:
        SystemExit: If command returns non-zero exit code
    """
    print(f"\n{'='*60}")
    print(f" {description}")
    print('='*60)
    
    result = subprocess.run(command, shell=True)
    
    if result.returncode != 0:
        print(f"\n❌ ERROR: {description} failed!")
        sys.exit(1)
    
    print(f"✓ {description} completed successfully!")


def main():
    """Build all Hash Verifier executables using PyInstaller.
    
    Creates three standalone Windows executables:
    - HashVerifier.exe: Main hash verification application
    - install.exe: Installation utility with context menu integration
    - uninstall.exe: Removal utility for complete cleanup
    
    Requires PyInstaller to be installed in the Python environment.
    """
    print("\n" + "="*60)
    print(" Hash Verifier - Build Script")
    print("="*60)
    
    # Verify PyInstaller is available
    print("\nChecking dependencies...")
    result = subprocess.run("pyinstaller --version", shell=True, capture_output=True)
    
    if result.returncode != 0:
        print("\n❌ PyInstaller is not installed!")
        print("\nPlease install it with:")
        print("  pip install pyinstaller")
        sys.exit(1)
    
    print("✓ PyInstaller is installed")
    
    # Clean previous build artifacts
    print("\nCleaning previous builds...")
    for folder in ['build', 'dist']:
        if os.path.exists(folder):
            shutil.rmtree(folder)
            print(f"  Removed {folder}/")
    
    # Remove old spec files generated by PyInstaller
    for spec_file in ['HashVerifier.spec', 'install.spec', 'uninstall.spec']:
        if os.path.exists(spec_file):
            os.remove(spec_file)
            print(f"  Removed {spec_file}")
    
    # Build main application executable
    run_command(
        "pyinstaller --onefile --windowed --name HashVerifier --clean hash_verifier.py",
        "Building HashVerifier.exe"
    )
    
    # Build installer executable
    run_command(
        "pyinstaller --onefile --windowed --name install --clean installer.py",
        "Building install.exe"
    )
    
    # Build uninstaller executable
    run_command(
        "pyinstaller --onefile --windowed --name uninstall --clean uninstaller.py",
        "Building uninstall.exe"
    )
    
    # Display success message with distribution instructions
    print("\n" + "="*60)
    print(" ✓ BUILD COMPLETE!")
    print("="*60)
    print("\nYour executables are in the 'dist' folder:")
    print("  - HashVerifier.exe (~15 MB)")
    print("  - install.exe (~10 MB)")
    print("  - uninstall.exe (~10 MB)")
    print("\nTo distribute:")
    print("  1. Copy all 3 .exe files to a folder")
    print("  2. Zip them up")
    print("  3. Users run install.exe to add context menu")
    print("\nDone! 🎉")


if __name__ == "__main__":
    main()
